## Goal

Develop a chart statistics table that summarizes the long-term chart performance of individual songs.

### Tasks

- Load cleaned chart history
- Load song table
- Link `song_id` to chart history
- Explore and define chart metrics
- Validate aggregation results
- Export chart statistics

In [1]:
from pathlib import Path
import pandas as pd

In [2]:
# Load Datasets

project_path = Path.cwd().parent
interim_path = project_path / 'data' / 'interim'

chart_history = pd.read_csv(interim_path/'uk_chart_history_clean.csv')
songs = pd.read_csv(interim_path/'songs.csv')

### Validate Datasets

The cleaned chart history and song table are loaded and validated before the song identifiers are linked.

In [3]:
songs.info()

<class 'pandas.DataFrame'>
RangeIndex: 36655 entries, 0 to 36654
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   song_id  36655 non-null  int64
 1   Song     36655 non-null  str
 2   Artist   36655 non-null  str
dtypes: int64(1), str(2)
memory usage: 859.2 KB

In [4]:
chart_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 210882 entries, 0 to 210881
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Song            210882 non-null  str
 1   Artist          210837 non-null  str
 2   Position        210882 non-null  int64
 3   Last Week       210882 non-null  str
 4   Peak            210882 non-null  int64
 5   Weeks on Chart  210882 non-null  int64
 6   Week            210882 non-null  str
dtypes: int64(3), str(4)
memory usage: 11.3 MB

In [5]:
chart_history = chart_history.merge(
    songs,
    on=['Song', 'Artist'],
    how='left'
)
chart_history = chart_history[
    ['song_id',
     'Song',
     'Artist',
     'Position',
     'Last Week',
     'Peak',
     'Weeks on Chart',
     'Week']
]

chart_history.head()

,song_id,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
0,1.0,SAVE YOUR LOVE,RENEE AND RENATO,1,LW:1,1,11,2 January 1983- 8 January 1983
1,2.0,YOU CAN'T HURRY LOVE,PHIL COLLINS,2,LW:6,2,6,2 January 1983- 8 January 1983
2,3.0,A WINTER'S TALE,DAVID ESSEX,3,LW:7,3,5,2 January 1983- 8 January 1983
3,4.0,BEST YEARS OF OUR LIVES,MODERN ROMANCE,4,LW:8,4,9,2 January 1983- 8 January 1983
4,5.0,OUR HOUSE,MADNESS,5,LW:5,5,7,2 January 1983- 8 January 1983

### Data quality correction

Duplicate chart entries occurring within the same chart week were identified
during the chart analysis. These entries create artificial overlapping chart
runs and are excluded from subsequent statistical calculations.

In [6]:
songs_to_delete = [{'song_id': 13496.0,
                    'Position': 57,
                    'Last Week': 'LW:New',
                    'Week': '3 September 1995- 9 September 1995'},
                    {'song_id': 13496.0,
                     'Position': 76,
                     'Last Week': 'LW:57',
                     'Week': '10 September 1995- 16 September 1995'},
                    {'song_id': 13965.0,
                     'Position': 91,
                     'Last Week': 'LW:New',
                     'Week': '24 December 1995- 30 December 1995'},
                    {'song_id': 13966.0,
                     'Position': 61,
                     'Last Week': 'LW:New',
                     'Week': '17 December 1995- 23 December 1995'},
                    {'song_id': 9155.0,
                     'Position': 19,
                     'Last Week': 'LW:New',
                     'Week': '3 January 1993- 9 January 1993'},
                    {'song_id': 8803.0,
                     'Position': 21,
                     'Last Week': 'LW:New',
                     'Week': '18 August 1991- 24 August 1991'},
                    {'song_id': 9061.0,
                     'Position': 22,
                     'Last Week': 'LW:New',
                     'Week': '24 November 1991- 30 November 1991'},
                    {'song_id': 10319.0,
                     'Position': 24,
                     'Last Week': 'LW:New',
                     'Week': '31 January 1993- 6 February 1993'},
                    {'song_id': 11079.0,
                     'Position': 36,
                     'Last Week': 'LW:New',
                     'Week': '17 October 1993- 23 October 1993'} ,
                    {'song_id': 11002.0,
                     'Position': 29,
                     'Last Week': 'LW:New',
                     'Week': '19 September 1993- 25 September 1993'}]

affected_song_ids = {item['song_id'] for item in songs_to_delete}

print(f'Number of affected songs: {len(affected_song_ids)}')

Number of affected songs: 9

In [7]:
print(f'Chart history rows before correction: {len(chart_history)}')

Chart history rows before correction: 210882

In [8]:
for item in songs_to_delete:
    mask = ((chart_history['song_id'] == item['song_id']) &
            (chart_history['Position'] == item['Position']) &
            (chart_history['Last Week'] == item['Last Week']) &
            (chart_history['Week'] == item['Week']))
    
    chart_history = chart_history.loc[~mask].copy()

In [9]:
print(f'Chart history rows after correction: {len(chart_history)}')

Chart history rows after correction: 210872

In [10]:
chart_history.info()

<class 'pandas.DataFrame'>
Index: 210872 entries, 0 to 210881
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   song_id         210827 non-null  float64
 1   Song            210872 non-null  str
 2   Artist          210827 non-null  str
 3   Position        210872 non-null  int64
 4   Last Week       210872 non-null  str
 5   Peak            210872 non-null  int64
 6   Weeks on Chart  210872 non-null  int64
 7   Week            210872 non-null  str
dtypes: float64(1), int64(3), str(4)
memory usage: 14.5 MB

## Explore Individual Song Histories

Selected songs are examined to identify meaningful chart metrics and recurring chart patterns.

These observations guide the design of the chart statistics table.

In [11]:
song_history = chart_history[
    (chart_history['Song'] == 'OUR HOUSE') &
    (chart_history['Artist'] == 'MADNESS')
]

song_history

,song_id,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
4,5.0,OUR HOUSE,MADNESS,5,LW:5,5,7,2 January 1983- 8 January 1983
112,5.0,OUR HOUSE,MADNESS,13,LW:5,5,8,9 January 1983- 15 January 1983
208,5.0,OUR HOUSE,MADNESS,10,LW:13,5,9,16 January 1983- 22 January 1983
319,5.0,OUR HOUSE,MADNESS,21,LW:10,5,10,23 January 1983- 29 January 1983
433,5.0,OUR HOUSE,MADNESS,35,LW:21,5,11,30 January 1983- 5 February 1983
551,5.0,OUR HOUSE,MADNESS,53,LW:35,5,12,6 February 1983- 12 February 1983
671,5.0,OUR HOUSE,MADNESS,73,LW:53,5,13,13 February 1983- 19 February 1983
149375,5.0,OUR HOUSE,MADNESS,92,LW:RE,5,14,10 June 2012- 16 June 2012
150382,5.0,OUR HOUSE,MADNESS,99,LW:RE,5,15,19 August 2012- 25 August 2012

In [12]:
song_history = chart_history[
    (chart_history['Song'] == 'RUNNING UP THAT HILL') &
    (chart_history['Artist'] == 'KATE BUSH')
]

song_history

,song_id,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
13596,2448.0,RUNNING UP THAT HILL,KATE BUSH,9,LW:New,9,1,11 August 1985- 17 August 1985
13691,2448.0,RUNNING UP THAT HILL,KATE BUSH,4,LW:9,4,2,18 August 1985- 24 August 1985
13789,2448.0,RUNNING UP THAT HILL,KATE BUSH,3,LW:4,3,3,25 August 1985- 31 August 1985
13891,2448.0,RUNNING UP THAT HILL,KATE BUSH,5,LW:3,3,4,1 September 1985- 7 September 1985
13994,2448.0,RUNNING UP THAT HILL,KATE BUSH,8,LW:5,3,5,8 September 1985- 14 September 1985
14101,2448.0,RUNNING UP THAT HILL,KATE BUSH,15,LW:8,3,6,15 September 1985- 21 September 1985
14209,2448.0,RUNNING UP THAT HILL,KATE BUSH,23,LW:15,3,7,22 September 1985- 28 September 1985
14319,2448.0,RUNNING UP THAT HILL,KATE BUSH,33,LW:23,3,8,29 September 1985- 5 October 1985
14435,2448.0,RUNNING UP THAT HILL,KATE BUSH,49,LW:33,3,9,6 October 1985- 12 October 1985
14547,2448.0,RUNNING UP THAT HILL,KATE BUSH,61,LW:49,3,10,13 October 1985- 19 October 1985
14661,2448.0,RUNNING UP THAT HILL,KATE BUSH,75,LW:61,3,11,20 October 1985- 26 October 1985
148934,2448.0,RUNNING UP THAT HILL,KATE BUSH,51,LW:RE,3,12,13 May 2012- 19 May 2012
150289,2448.0,RUNNING UP THAT HILL,KATE BUSH,6,LW:RE,3,13,19 August 2012- 25 August 2012
150416,2448.0,RUNNING UP THAT HILL,KATE BUSH,33,LW:6,3,14,26 August 2012- 1 September 2012
150546,2448.0,RUNNING UP THAT HILL,KATE BUSH,63,LW:33,3,15,2 September 2012- 8 September 2012
160934,2448.0,RUNNING UP THAT HILL,KATE BUSH,51,LW:RE,3,16,31 August 2014- 6 September 2014
161081,2448.0,RUNNING UP THAT HILL,KATE BUSH,98,LW:51,3,17,7 September 2014- 13 September 2014
201291,2448.0,RUNNING UP THAT HILL,KATE BUSH,8,LW:RE,3,18,3 June 2022- 9 June 2022
201385,2448.0,RUNNING UP THAT HILL,KATE BUSH,2,LW:8,2,19,10 June 2022- 16 June 2022
201484,2448.0,RUNNING UP THAT HILL,KATE BUSH,1,LW:2,1,20,17 June 2022- 23 June 2022
201584,2448.0,RUNNING UP THAT HILL,KATE BUSH,1,LW:1,1,21,24 June 2022- 30 June 2022
201684,2448.0,RUNNING UP THAT HILL,KATE BUSH,1,LW:1,1,22,1 July 2022- 7 July 2022
201786,2448.0,RUNNING UP THAT HILL,KATE BUSH,3,LW:1,1,23,8 July 2022- 14 July 2022
201888,2448.0,RUNNING UP THAT HILL,KATE BUSH,5,LW:3,1,24,15 July 2022- 21 July 2022
201991,2448.0,RUNNING UP THAT HILL,KATE BUSH,8,LW:5,1,25,22 July 2022- 28 July 2022
202092,2448.0,RUNNING UP THAT HILL,KATE BUSH,9,LW:8,1,26,29 July 2022- 4 August 2022
202192,2448.0,RUNNING UP THAT HILL,KATE BUSH,9,LW:9,1,27,5 August 2022- 11 August 2022
202297,2448.0,RUNNING UP THAT HILL,KATE BUSH,14,LW:9,1,28,12 August 2022- 18 August 2022
202402,2448.0,RUNNING UP THAT HILL,KATE BUSH,19,LW:14,1,29,19 August 2022- 25 August 2022
202503,2448.0,RUNNING UP THAT HILL,KATE BUSH,20,LW:19,1,30,26 August 2022- 1 September 2022
202606,2448.0,RUNNING UP THAT HILL,KATE BUSH,23,LW:20,1,31,2 September 2022- 8 September 2022
202705,2448.0,RUNNING UP THAT HILL,KATE BUSH,22,LW:23,1,32,9 September 2022- 15 September 2022
202808,2448.0,RUNNING UP THAT HILL,KATE BUSH,25,LW:22,1,33,16 September 2022- 22 September 2022
202913,2448.0,RUNNING UP THAT HILL,KATE BUSH,30,LW:25,1,34,23 September 2022- 29 September 2022
203015,2448.0,RUNNING UP THAT HILL,KATE BUSH,32,LW:30,1,35,30 September 2022- 6 October 2022
203117,2448.0,RUNNING UP THAT HILL,KATE BUSH,34,LW:32,1,36,7 October 2022- 13 October 2022
203218,2448.0,RUNNING UP THAT HILL,KATE BUSH,35,LW:34,1,37,14 October 2022- 20 October 2022
203335,2448.0,RUNNING UP THAT HILL,KATE BUSH,52,LW:35,1,38,21 October 2022- 27 October 2022
203431,2448.0,RUNNING UP THAT HILL,KATE BUSH,48,LW:52,1,39,28 October 2022- 3 November 2022
203527,2448.0,RUNNING UP THAT HILL,KATE BUSH,44,LW:48,1,40,4 November 2022- 10 November 2022
203638,2448.0,RUNNING UP THAT HILL,KATE BUSH,55,LW:44,1,41,11 November 2022- 17 November 2022
203743,2448.0,RUNNING UP THAT HILL,KATE BUSH,60,LW:55,1,42,18 November 2022- 24 November 2022
203850,2448.0,RUNNING UP THAT HILL,KATE BUSH,67,LW:60,1,43,25 November 2022- 1 December 2022
203965,2448.0,RUNNING UP THAT HILL,KATE BUSH,82,LW:67,1,44,2 December 2022- 8 December 2022
204081,2448.0,RUNNING UP THAT HILL,KATE BUSH,98,LW:82,1,45,9 December 2022- 15 December 2022
204438,2448.0,RUNNING UP THAT HILL,KATE BUSH,55,LW:RE,1,46,6 January 2023- 12 January 2023
204560,2448.0,RUNNING UP THAT HILL,KATE BUSH,77,LW:55,1,47,13 January 2023- 19 January 2023
204671,2448.0,RUNNING UP THAT HILL,KATE BUSH,88,LW:77,1,48,20 January 2023- 26 January 2023
204773,2448.0,RUNNING UP THAT HILL,KATE BUSH,90,LW:88,1,49,27 January 2023- 2 February 2023
204874,2448.0,RUNNING UP THAT HILL,KATE BUSH,91,LW:90,1,50,3 February 2023- 9 February 2023
204969,2448.0,RUNNING UP THAT HILL,KATE BUSH,86,LW:91,1,51,10 February 2023- 16 February 2023
205381,2448.0,RUNNING UP THAT HILL,KATE BUSH,98,LW:RE,1,52,10 March 2023- 16 March 2023

In [13]:
song_history = chart_history[
    chart_history['Song'] == 'BARBIE GIRL'
]

song_history

,song_id,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
73193,16442.0,BARBIE GIRL,AQUA,2,LW:New,2,1,19 October 1997- 25 October 1997
73292,16442.0,BARBIE GIRL,AQUA,1,LW:2,1,2,26 October 1997- 1 November 1997
73392,16442.0,BARBIE GIRL,AQUA,1,LW:1,1,3,2 November 1997- 8 November 1997
73492,16442.0,BARBIE GIRL,AQUA,1,LW:1,1,4,9 November 1997- 15 November 1997
73592,16442.0,BARBIE GIRL,AQUA,1,LW:1,1,5,16 November 1997- 22 November 1997
73693,16442.0,BARBIE GIRL,AQUA,2,LW:1,1,6,23 November 1997- 29 November 1997
73794,16442.0,BARBIE GIRL,AQUA,3,LW:2,1,7,30 November 1997- 6 December 1997
73894,16442.0,BARBIE GIRL,AQUA,3,LW:3,1,8,7 December 1997- 13 December 1997
73994,16442.0,BARBIE GIRL,AQUA,3,LW:3,1,9,14 December 1997- 20 December 1997
74097,16442.0,BARBIE GIRL,AQUA,6,LW:3,1,10,21 December 1997- 27 December 1997
74301,16442.0,BARBIE GIRL,AQUA,10,LW:7,1,12,4 January 1998- 10 January 1998
74409,16442.0,BARBIE GIRL,AQUA,18,LW:10,1,13,11 January 1998- 17 January 1998
74515,16442.0,BARBIE GIRL,AQUA,24,LW:18,1,14,18 January 1998- 24 January 1998
74622,16442.0,BARBIE GIRL,AQUA,31,LW:24,1,15,25 January 1998- 31 January 1998
74725,16442.0,BARBIE GIRL,AQUA,34,LW:31,1,16,1 February 1998- 7 February 1998
74827,16442.0,BARBIE GIRL,AQUA,36,LW:34,1,17,8 February 1998- 14 February 1998
74930,16442.0,BARBIE GIRL,AQUA,39,LW:36,1,18,15 February 1998- 21 February 1998
75036,16442.0,BARBIE GIRL,AQUA,45,LW:39,1,19,22 February 1998- 28 February 1998
75147,16442.0,BARBIE GIRL,AQUA,57,LW:45,1,20,1 March 1998- 7 March 1998
75249,16442.0,BARBIE GIRL,AQUA,60,LW:57,1,21,8 March 1998- 14 March 1998
75346,16442.0,BARBIE GIRL,AQUA,58,LW:60,1,22,15 March 1998- 21 March 1998
75451,16442.0,BARBIE GIRL,AQUA,63,LW:58,1,23,22 March 1998- 28 March 1998
75558,16442.0,BARBIE GIRL,AQUA,70,LW:63,1,24,29 March 1998- 4 April 1998
75771,16442.0,BARBIE GIRL,AQUA,83,LW:RE,1,25,12 April 1998- 18 April 1998
75854,16442.0,BARBIE GIRL,AQUA,66,LW:83,1,26,19 April 1998- 25 April 1998
75961,16442.0,BARBIE GIRL,AQUA,73,LW:66,1,27,26 April 1998- 2 May 1998
125109,27920.0,BARBIE GIRL,SAMANDA,26,LW:New,26,1,14 October 2007- 20 October 2007
125218,27920.0,BARBIE GIRL,SAMANDA,35,LW:26,26,2,21 October 2007- 27 October 2007
125340,27920.0,BARBIE GIRL,SAMANDA,57,LW:35,26,3,28 October 2007- 3 November 2007
125463,27920.0,BARBIE GIRL,SAMANDA,80,LW:57,26,4,4 November 2007- 10 November 2007
125573,27920.0,BARBIE GIRL,SAMANDA,90,LW:80,26,5,11 November 2007- 17 November 2007
207323,16442.0,BARBIE GIRL,AQUA,40,LW:RE,1,28,28 July 2023- 3 August 2023
207425,16442.0,BARBIE GIRL,AQUA,42,LW:40,1,29,4 August 2023- 10 August 2023
207532,16442.0,BARBIE GIRL,AQUA,50,LW:42,1,30,11 August 2023- 17 August 2023
207638,16442.0,BARBIE GIRL,AQUA,57,LW:50,1,31,18 August 2023- 24 August 2023

## Design Chart Metrics

The chart history is explored to define meaningful statistics that describe the long-term chart performance of individual songs.

Each metric is developed and validated individually before creating the final chart statistics table.

### Peak Position

The peak position represents the highest chart position reached by each song.

It is calculated as the minimum chart position across the complete chart history of a song.

In [14]:
peak_position = (
    chart_history
    .groupby('song_id')['Position']
    .min()
    .rename('peak_position')
)

peak_position.head()

song_id
1.0    1
2.0    1
3.0    2
4.0    4
5.0    5
Name: peak_position, dtype: int64

In [15]:
# Metric Validation

validate_song = chart_history['song_id'] == 5
chart_history.loc[validate_song,:]

,song_id,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
4,5.0,OUR HOUSE,MADNESS,5,LW:5,5,7,2 January 1983- 8 January 1983
112,5.0,OUR HOUSE,MADNESS,13,LW:5,5,8,9 January 1983- 15 January 1983
208,5.0,OUR HOUSE,MADNESS,10,LW:13,5,9,16 January 1983- 22 January 1983
319,5.0,OUR HOUSE,MADNESS,21,LW:10,5,10,23 January 1983- 29 January 1983
433,5.0,OUR HOUSE,MADNESS,35,LW:21,5,11,30 January 1983- 5 February 1983
551,5.0,OUR HOUSE,MADNESS,53,LW:35,5,12,6 February 1983- 12 February 1983
671,5.0,OUR HOUSE,MADNESS,73,LW:53,5,13,13 February 1983- 19 February 1983
149375,5.0,OUR HOUSE,MADNESS,92,LW:RE,5,14,10 June 2012- 16 June 2012
150382,5.0,OUR HOUSE,MADNESS,99,LW:RE,5,15,19 August 2012- 25 August 2012

### Total Chart Weeks

The official total chart duration is derived from the cumulative
`Weeks on Chart` value provided in the original chart dataset.

This metric reflects the complete chart history of a song, including chart
weeks before the observation period beginning in 1983.

An additional metric (`observed_chart_weeks`) is calculated separately to
describe only the chart appearances contained within the observation period.

In [16]:
total_chart_weeks = (chart_history
                    .groupby('song_id')['Weeks on Chart']
                    .max()
                    .rename('total_chart_weeks')
                    )

print(f'Number of total chart weeks: {total_chart_weeks.loc[5]}')

Number of total chart weeks: 15

### Observed Chart Weeks

The number of observed chart weeks is calculated by counting all chart
appearances within the available dataset.

Unlike the official chart duration, this metric only reflects the observation
period covered by this project.

In [17]:
observed_chart_weeks = (chart_history
                        .groupby('song_id')
                        .size()
                        .rename('observed_chart_weeks')
                        )

print(f'Number of observed chart weeks: {observed_chart_weeks.loc[5]}')

Number of observed chart weeks: 9

### Weeks at Number One

The number of observed weeks a song reached the number one position is
calculated by counting all chart entries with a chart position equal to one.

This metric only reflects chart appearances contained within the observation
period covered by this project.

In [18]:
weeks_top_1 = (chart_history[chart_history['Position'] == 1]
                .groupby('song_id')
                .size()
                .rename('weeks_top_1')
                )

chart_history[chart_history['Position'] == 1].head()

,song_id,Song,Artist,Position,Last Week,Peak,Weeks on Chart,Week
0,1.0,SAVE YOUR LOVE,RENEE AND RENATO,1,LW:1,1,11,2 January 1983- 8 January 1983
100,2.0,YOU CAN'T HURRY LOVE,PHIL COLLINS,1,LW:2,1,7,9 January 1983- 15 January 1983
199,2.0,YOU CAN'T HURRY LOVE,PHIL COLLINS,1,LW:1,1,8,16 January 1983- 22 January 1983
299,38.0,DOWN UNDER,MEN AT WORK,1,LW:2,1,4,23 January 1983- 29 January 1983
399,38.0,DOWN UNDER,MEN AT WORK,1,LW:1,1,5,30 January 1983- 5 February 1983

In [19]:
print(f'Weeks at Number 1: {weeks_top_1.loc[2]}')

Weeks at Number 1: 2

### Weeks in Top 10

The number of observed weeks spent within the Top 10 is calculated by counting
all chart entries with positions from 1 to 10.

This metric only reflects chart appearances contained within the observation
period covered by this project.

In [20]:
weeks_top_10 = (chart_history[chart_history['Position'] <= 10]
                .groupby('song_id')
                .size()
                .rename('weeks_top_10')
                )
print(f'Weeks in Top 10: {weeks_top_10.loc[5]}')

Weeks in Top 10: 2

### Weeks in Top 50

The number of observed weeks spent within the Top 50 is calculated by counting
all chart entries with positions from 1 to 50.

This metric only reflects chart appearances contained within the observation
period covered by this project.

In [21]:
weeks_top_50 = (chart_history[chart_history['Position'] <= 50]
                .groupby('song_id')
                .size()
                .rename('weeks_top_50')
                )
print(f'Weeks in Top 50: {weeks_top_50.loc[5]}')

Weeks in Top 50: 5

## Create Chart Statistics Table

The individual chart metrics are combined into a single table using the unique
song identifier.

This table summarizes the chart performance of every song and serves as the
foundation for subsequent analyses and Spotify enrichment.

In [22]:
chart_statistics = songs.copy()
chart_statistics.head()

   song_id                     Song            Artist
0        1           SAVE YOUR LOVE  RENEE AND RENATO
1        2     YOU CAN'T HURRY LOVE      PHIL COLLINS
2        3          A WINTER'S TALE       DAVID ESSEX
3        4  BEST YEARS OF OUR LIVES    MODERN ROMANCE
4        5                OUR HOUSE           MADNESS

In [23]:
# Add Peak Position

chart_statistics = (chart_statistics
                    .merge(peak_position,
                           on='song_id',
                           how='left')
                    )

In [24]:
# Add Total Chart Weeks

chart_statistics = (chart_statistics
                    .merge(total_chart_weeks,
                           on='song_id',
                           how='left')
                    )

In [25]:
# Add Observed Chart Weeks

chart_statistics = (chart_statistics
                    .merge(observed_chart_weeks,
                           on='song_id',
                           how='left')
                    )

In [26]:
# Add Weeks at Number One

chart_statistics = (chart_statistics
                    .merge(weeks_top_1,
                           on='song_id',
                           how='left')
                    )

In [27]:
# Songs without number-one weeks receive a value of 0

chart_statistics['weeks_top_1'] = (chart_statistics['weeks_top_1']
                                   .fillna(0)
                                   .astype(int)
                                   )

In [28]:
# Add Weeks in Top 10

chart_statistics = (chart_statistics
                    .merge(weeks_top_10,
                           on='song_id',
                           how='left')
                    )

In [29]:
# Replace missing values of count-based metrics with 0.

chart_statistics['weeks_top_10'] = (chart_statistics['weeks_top_10']
                                   .fillna(0)
                                   .astype(int)
                                   )

In [30]:
# Add Weeks in Top 50

chart_statistics = (chart_statistics
                    .merge(weeks_top_50,
                           on='song_id',
                           how='left')
                    )

In [31]:
chart_statistics['weeks_top_50'] = (chart_statistics['weeks_top_50']
                                   .fillna(0)
                                   .astype(int)
                                   )

### Validate Chart Statistics

The completed chart statistics table is reviewed to verify that the calculated
metrics have been merged correctly.

In [32]:
chart_statistics

,song_id,Song,Artist,peak_position,total_chart_weeks,observed_chart_weeks,weeks_top_1,weeks_top_10,weeks_top_50
0,1,SAVE YOUR LOVE,RENEE AND RENATO,1,16,6,1,2,5
1,2,YOU CAN'T HURRY LOVE,PHIL COLLINS,1,16,11,2,6,9
2,3,A WINTER'S TALE,DAVID ESSEX,2,10,6,0,3,6
3,4,BEST YEARS OF OUR LIVES,MODERN ROMANCE,4,13,5,0,2,5
4,5,OUR HOUSE,MADNESS,5,15,9,0,2,5
...,...,...,...,...,...,...,...,...,...
36650,36651,JUMP,TYLA/GUNNA/SKILLIBENG,80,1,1,0,0,0
36651,36652,ART,TYLA,85,1,1,0,0,0
36652,36653,WILDFLOWER AND BARLEY,HOZIER/ALLISON RUSSELL,86,1,1,0,0,0
36653,36654,EMPI NOW,HOZIER,92,1,1,0,0,0
36654,36655,SOMEDAY I'LL GET IT,ALEK OLSEN,98,1,1,0,0,0

In [33]:
chart_statistics.info()

<class 'pandas.DataFrame'>
RangeIndex: 36655 entries, 0 to 36654
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   song_id               36655 non-null  int64
 1   Song                  36655 non-null  str
 2   Artist                36655 non-null  str
 3   peak_position         36655 non-null  int64
 4   total_chart_weeks     36655 non-null  int64
 5   observed_chart_weeks  36655 non-null  int64
 6   weeks_top_1           36655 non-null  int64
 7   weeks_top_10          36655 non-null  int64
 8   weeks_top_50          36655 non-null  int64
dtypes: int64(7), str(2)
memory usage: 2.5 MB

In [34]:
print(chart_statistics.shape)

(36655, 9)

In [35]:
## Export Chart Statistics

interim_path = project_path / 'data' / 'interim'

chart_statistics.to_csv(interim_path/'chart_statistics.csv', index=False)